### ISSUE TITLE
10₺ verdiğimiz cam filmi sorunu

### ISSUE THREAD

**Issue by BerkayKoksal** [InceptionNetwork/issues#16]
**Sunucu Adı:İnception Roleplay

**Hata Açıklaması:**
10₺ cam filmi alıyoruz fakat hiçbir şekilde bizi gizlemiyor millet mix yapmaya devam ediyor uzaktan cam filmi yakından isim gözüküyor

**Ekran Görüntüleri:**
Sorununuzu ekran görüntüleriyle anlatın. (imgur.com)

**Ek Açıklama:**
`Eğer sorunun nasıl çözüleceğine dair fikriniz varsa yazın.`

**Comment by cleopatradev** [comment]
Zaten böyle bir sorun açıldı: #15
