### ISSUE TITLE
Hız bulanıklığı kaldırılsın

### ISSUE THREAD

**Issue by Plutonss** [InceptionNetwork/issues#19]
**Sunucu Adı:** Inception Roleplay

**Açıklama:**
GTA'da standart olarak gelen, adını bilmediğim, "araç hız bulanıklığı" kaldırılsın.

**Ekran Görüntüleri:**
https://i.imgyukle.com/2021/02/14/LLSmtH.png

**Comment by cleopatradev** [comment]
Sorun çözüldü.
