### ISSUE TITLE
Cam Filmi Problemi

### ISSUE THREAD

**Issue by rootdoki** [InceptionNetwork/issues#22]
**Sunucu Adı:** Inception Roleplay

**Hata Açıklaması:**
Cam filmi bulunan bir araçtan indikten sonra insek bile NameTag kısmında araçta olmamamıza rağmen örn; Cam Filmi(#3131) olarak gözüküyor.

**Ekran Görüntüleri:**
Bulunmuyor.

**Ek Açıklama:**
Araçtan inince isim gözükeceğine Cam Filmi(#id) gözüküyor, bu düzeltilebilir.

**Comment by cleopatradev** [comment]
#15
