### ISSUE TITLE
Market PET Alışverişi

### ISSUE THREAD

**Issue by eserjpeg** [InceptionNetwork/issues#3]
**Sunucu Adı:** Inception Roleplay, Janti Roleplay

**Hata Açıklaması:**
/market üzerinden 2. bir PET alışverişi gerçekleştirdikten sonra, iki PET'e de erişemiyoruz.

**Ekran Görüntüleri:**

**Ek Açıklama**
Market üzerinden 2. PET alışverişini engellersek sorun çözülebilir.

**Comment by cleopatradev** [comment]
Sorun çözüldü.
