### ISSUE TITLE
@inception Roleplay /vergiode ve /atm  Kodu istegi

### ISSUE THREAD

**Issue by hasancepik2727** [InceptionNetwork/issues#32]
İnception Roleplay

Merhabalar Benim oyunda yaşadıgım bi sorun var sadece başlangıç ​​roleplayde sağ tıkım çalışmıyor pc formatladım herşey yaptım düzelmedi böyle yüzünden 3-4 tane bağış aracım vergiden'den silindi Sizden istegim Mesela vergi ödemede adama sağ tıklamak yerine / vergiode id yapıp vergisini ödesek bankadada / atm yazıp para cekebilsek tek istegim bunlar lütfen :))

**Comment by eserjpeg** [comment]
Uygunsuz şablon.
