### ISSUE TITLE
Starfish Greenzone

### ISSUE THREAD

**Issue by rootdoki** [InceptionNetwork/issues#35]
**Sunucu Adı:** 
Inception Roleplay

**Açıklama:**
/hediyeal ve özellikle Starfish gibi bölgeler greenzone olmalı yani oyuncular orada eline sopa/bıçak vs. gibi şeyler alıp mouse sol click kullanamasın. Bunun sebebi Starfish'de çok fazla Kavga , Troll , DM gibi şeyler oluyor. 

**Ekran Görüntüleri:**
Yok

**Comment by cleopatradev** [comment]
Burası roleplay sunucusu, freeroam değil.
