### ISSUE TITLE
Sohbet Üzerinde Sembol

### ISSUE THREAD

**Issue by eserjpeg** [InceptionNetwork/issues#4]
**Sunucu Adı:** Inception Roleplay

**Hata Açıklaması:**
VIP üyelerimiz maske ile /me, /do komutlarını kullandıklarında veya ateş ettiğinde #103202 yazması gerekirken renk kodu algılıyor.

**Ekran Görüntüleri:**

**Ek Açıklama:**
`#` sembolünü `>` sembolüne çevirirsek sorun ortadan kalkacaktır.

**Comment by cleopatradev** [comment]
Sorun çözüldü.
