### ISSUE TITLE
HUD Önerisi

### ISSUE THREAD

**Issue by ENS4R** [InceptionNetwork/issues#45]
**Sunucu Adı:** Sunucu adını yazın İnception Roleplay

**Açıklama:**
İstediğiniz sistemi detaylıca açıklayın.
Merhablar Öncelikle 2018 Yılından beri inception oyuncusu olarak bu öneriyi size ediyorumm 
hud olarak yeni yapılan hud gözlere bence etkileyici olarak çarpmıyor bence esi hud geri gelmeli çünkü daha etkileyici bence
--- yada edithud geri getirilip oyuncuların istediğiği hudu yapmaları ama tabikide bence herkeste bu hudun olması daha doğru olabilir... 
fotoğrafta işaretlediğim gibi hudlar gelse çok güzel olabilir tabikide mini radar hariç :)

**Ekran Görüntüleri:** https://hizliresim.com/bLgib3
Eğer varsa lütfen ekran görüntüleriyle isteğinizi detaylandırın, anlamamıza yardımcı olun.
ekran görüntüsü
https://hizliresim.com/bLgib3
https://hizliresim.com/bLgib3

**Comment by eserjpeg** [comment]
Uygunsuz şablon.
