### ISSUE TITLE
Birlik Kurma Sorunu

### ISSUE THREAD

**Issue by eserjpeg** [InceptionNetwork/issues#5]
**Sunucu Adı:** Inception Roleplay

**Hata Açıklaması:**
/birlikkur paneli üzerinde Oluştur butonu işlevini yerine getirmiyor.

**Ekran Görüntüleri:**
Hata Çıktısı: https://i.imgur.com/PQiBL8e.png

**Ek Açıklama:**

**Comment by cleopatradev** [comment]
Sorun çözüldü.
