### ISSUE TITLE
Sohbet Kayıt Sorunu

### ISSUE THREAD

**Issue by eserjpeg** [InceptionNetwork/issues#9]
**Sunucu Adı:** Inception Roleplay

**Hata Açıklaması:**
Sohbet kayıt sistemi üzerinde yalnızca belirli mesajlar kayıtlanıyor, bir sorun var kontrol edebilir misiniz?

**Ekran Görüntüleri:**

**Ek Açıklama:**

**Comment by cleopatradev** [comment]
Sorun çözüldü.
